name: Post JSON File to Two URLs 

on: 
  push: 
    branches: 
      - main  # Runs only when pushing to the main branch 
    workflow_dispatch:  # Allows manual trigger 

jobs: 
  post_json: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v3 

      - name: Send JSON Data to First URL 
        run: | 
          curl -X POST "https://tandem.autodesk.com/pages/facilities/urn:adsk.dtt:gvdO2SmwTJqxyjUakMRBnA?selection=gvdO2SmwTJqxyjUakMRBnAEAAADz3BmUloNKeZQIw30ltXiFAAAAAA" \ 
            -H "Content-Type: application/json" \ 
            -d @stream.json

      - name: Send JSON Data to Second URL 
        run: | 
          curl -X POST "https://tandem.autodesk.com/pages/facilities/urn:adsk.dtt:gvdO2SmwTJqxyjUakMRBnA?selection=gvdO2SmwTJqxyjUakMRBnAEAAAD_xmrqiGxAUrf8PZQw4EQNAAAAAA" \ 
            -H "Content-Type: application/json" \ 
            -d @stream.json 
